# An attempt at running the lib unit tests using python 2.6 and python 2.7 via TravisCI
# The idea here is to start small, add-in building and running the test binaries under GDB, 
# Then use QEMU (or some better method) to test against x86, x86_64, and ARM

language: python
python:
  - "2.6"
  - "2.7"

# whitelist
branches:
  only:
    - integration

# command to install dependencies
install: "sudo apt-get --yes install gdb"

# build tests before running them (even though we aren't actually running them yet)
before_script: "cd exploitable/tests && make && cd ../.."

# command to run tests
script: 'gdb -ex "source lib/tests/unit_tests.py" -ex "quit"'
