# This is a travis-ci.org configuration script. This script performs 
# integration tests for the GDB 'exploitable' plugin on x86 and ARM target
# architectures when the associated git repo is checked into github. 
# The majority of the testing logic is contained in bash scripts 
# rather than this configuration file to support running the tests outside
# of travis-ci.
#
# Jonathan Foote
# jmfoote@loyola.edu

language: python
python:
  - "2.7"

# These are AWS keys. See http://docs.travis-ci.com/user/encryption-keys/
env:
  global:
    - secure: "KvlCtcQBL0U2cM8stCdLMHVHUrHY9qlycgNhbmIHeUq66zH9R0NQLALCuXL8KWMBgybeQ8CEQPzN0G4QOVcrmk5Qw5moXqZtkzW8ufc4uSm0332iCZJjUf5fRejqpWDL5YFwwFixgsi3s25Gq4dDM10h63Hc1FKtBTLUL6A074Q="
    - secure: "IlMvnc7UPFdry/s+OvAyqVmLoFScyBLYVmLgWc31e6pDfQRexsnRZBQgyKlDLF9TkUgAiWFNORecYgmuBhFWULe46e6mRWX0ngdpYu9ZYdl5pPNfZjLbFF3+TRhD6KDN8EkPzSP0TMlrpDHTs2rxgDIaq0YU3L0klmXaLQPskFg="
# whitelist
branches:
  only:
    - master

install:
  pip install boto

# command to run tests
script: '${TRAVIS_BUILD_DIR}/test/x86.sh && ${TRAVIS_BUILD_DIR}/test/arm.sh'
