# This is a travis-ci.org configuration script. This script performs 
# integration tests for the GDB 'exploitable' plugin on x86 and ARM target
# architectures when the associated git repo is checked into github. 
# The majority of the testing logic is contained in bash scripts 
# rather than this configuration file to support running the tests outside
# of travis-ci.
#
# Jonathan Foote
# jmfoote@loyola.edu

language: python
python:
  - "2.7"

env:
  global:
    - secure: "EmGbYiL38oPxim+s/llb0BQa0eBZjhKbUgsw2jxWALpYu9URJnMR27oZbRopoHzxaqCdHDBKyWgn+O8FwHNXJBa0m7Xos6CGcE3+6xRa/wIO5Q9xUlurrN+QQOJwg1Mu1SOWNq/jpNsCg3KBj2yTVtf/oNWziZjh3SyyOmuJwgA="
    - secure: "RWhV4njzgcKWlhKcBqCkbxZHHZX87Ic3qqlYjLOhDrJdv4lytWfJ5eDBq/TYm0zkGPqQl46LPCdwgu4lDiAI+A3mVW6P/wYQImhWntNMTT+ghTOUEAhYgtMWIJBWhSs70QxLgNsUBGwVow3Ou4hR/DeDyqUVRFHkqovX6yL+B/w="

# whitelist
branches:
  only:
    - integration

install:
  pip install boto

# command to run tests
script: '${TRAVIS_BUILD_DIR}/test/x86.sh && ${TRAVIS_BUILD_DIR}/test/arm.sh'
