# An attempt at running the lib unit tests using python 2.6 and python 2.7 via TravisCI
# The idea here is to start small, add-in building and running the test binaries under GDB, 
# Then use QEMU (or some better method) to test against x86, x86_64, and ARM

language: python
python:
  - "2.6"
  - "2.7"

env:
  global:
    - secure: "EmGbYiL38oPxim+s/llb0BQa0eBZjhKbUgsw2jxWALpYu9URJnMR27oZbRopoHzxaqCdHDBKyWgn+O8FwHNXJBa0m7Xos6CGcE3+6xRa/wIO5Q9xUlurrN+QQOJwg1Mu1SOWNq/jpNsCg3KBj2yTVtf/oNWziZjh3SyyOmuJwgA="
    - secure: "RWhV4njzgcKWlhKcBqCkbxZHHZX87Ic3qqlYjLOhDrJdv4lytWfJ5eDBq/TYm0zkGPqQl46LPCdwgu4lDiAI+A3mVW6P/wYQImhWntNMTT+ghTOUEAhYgtMWIJBWhSs70QxLgNsUBGwVow3Ou4hR/DeDyqUVRFHkqovX6yL+B/w="

# whitelist
branches:
  only:
    - integration

# command to install dependencies
#install: "sudo apt-get --yes install gdb"

# build tests before running them (even though we aren't actually running them yet)
#before_script: "cd exploitable/tests && make && cd ../.."

# command to run tests
#script: 'gdb -ex "source lib/tests/unit_tests.py" -ex "quit"'
script: './test/test-arm.sh'
